#!/bin/sh
# This is machine specific configurations

set -e

/bin/zsh << 'EOF'


echo "\`Status for Commercial Service\`\n"
echo "\`\`\`" | (aws elb describe-instance-health --load-balancer-name ELB-commercialService --output table| (echo "\`\`\`" && cat) && cat) > elb_log.txt
cat elb_logs.txt
sleep 1s;

EOF
