#!/bin/sh
# This is machine specific configurations

set -e

/bin/zsh << 'EOF'

cd ~/Projects/hubot/logs

echo "\`Status for FlightInfo Service\`\n"
echo "\`\`\`" | (aws elb describe-instance-health --load-balancer-name ELB-flightInfoService --output table| (echo "\`\`\`" && cat) && cat) > elb_log.txt
cat elb_log.txt
sleep 1s;

EOF
