#!/bin/sh
# This is machine specific configurations

set -e


echo "\`Status for Feedback Service\`\n"
echo "\`\`\`" | (aws elb describe-instance-health --load-balancer-name UAT-ELB-feedbackService --output table| (echo "\`\`\`" && cat) && cat) > elb_log.txt
cat elb_log.txt
sleep 1s;
