#!/bin/sh
# This is machine specific configurations

set -e

SCRIPT_PATH=$HUBOT_DIR/hubot/bash

echo "I started looking on the services health."
sleep 1s;
echo "Dont worry.. :blush:"

sleep 1s;

bash $SCRIPT_PATH/notify.sh
