#!/bin/sh
# This is machine specific configurations

set -e

/bin/zsh << 'EOF'

echo "\`Status for Notification Service\`\n"
echo "\`\`\`" | (aws elb describe-instance-health --load-balancer-name ELB-notificationService --output table| (echo "\`\`\`" && cat) && cat) > elb_log.txt
cat elb_log.txt
sleep 1s;

EOF
