#!/bin/sh
# This is machine specific configurations

set -e

echo "\`Status for Notification Service\`"
echo "\`\`\`" | (aws elb describe-instance-health --load-balancer-name UAT-ELB-NS --output table| (echo "\`\`\`" && cat) && cat) > elb_log.txt
cat elb_log.txt
sleep 1s;
