#!/bin/sh
# This is machine specific configurations

set -e

/bin/zsh << 'EOF'


echo "\`Status for Weather Service\`\n"
echo "\`\`\`" | (aws elb describe-instance-health --load-balancer-name UAT-ELB-weatherService --output table| (echo "\`\`\`" && cat) && cat) > elb_log.txt
cat elb_log.txt
sleep 1s;

EOF
